name: 
on: [push, pull_request, create, delete, issue_comment]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          
      - run: npm install

      - name: Lint
        run: npm run lint

      - name: NPM Test
        run: npm test
